[phases.setup]
aptPackages = ["libpq-dev", "apache2", "libapache2-mod-php"]

[phases.build]
commands = [
    "a2enmod rewrite",
    "rm /etc/apache2/sites-enabled/000-default.conf"
]

[start]
cmd = "apache2-foreground"